functionsDirectory = "/home/l0086/Documents/MY PROJECTS/Dockify/Dockify/netlify/functions"
functionsDirectoryOrigin = "ui"
plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/l0086/Documents/MY PROJECTS/Dockify/Dockify/dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/home/l0086/Documents/MY PROJECTS/Dockify/Dockify"
command = "npm run build"
functions = "/home/l0086/Documents/MY PROJECTS/Dockify/Dockify/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]